# -*- coding: utf-8 -*-
"""
config_wizard.py — 初始化与配置向导。

模块:
  - 首次启动向导（语言/协议/管理员/数据库/基础配置/测试连接/完成）
  - 配置文件管理（.env 生成 / 验证 / 备份 / 恢复 / 对比 / 模板 / 加密）
  - 数据库初始化（内存模拟：表结构/索引/种子数据/管理员账户）
  - 数据迁移（版本升级迁移计划/备份/回滚/验证/日志）
  - 服务管理（启动/停止/重启/状态/日志/开机自启/健康检查）

注意：不创建真实数据库表，全部用内存字典模拟。
"""

from __future__ import annotations

import hashlib
import os
import secrets
import time
from typing import Any, Dict, List, Optional

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# =========================================================================== #
# 1. 首次启动向导
# =========================================================================== #
WIZARD_STEPS: List[Dict[str, Any]] = [
    {"step": 1, "key": "language",    "title": "语言选择",       "description": "选择系统界面语言",
     "options": ["zh-CN", "en-US", "ja-JP", "ko-KR"]},
    {"step": 2, "key": "license",     "title": "许可证协议",     "description": "阅读并接受 EULA"},
    {"step": 3, "key": "admin",       "title": "管理员账户",     "description": "创建管理员账户"},
    {"step": 4, "key": "database",    "title": "数据库初始化",   "description": "初始化数据库连接"},
    {"step": 5, "key": "basic_config","title": "基础配置",       "description": "端口/日志/密钥"},
    {"step": 6, "key": "test_conn",   "title": "测试连接",       "description": "验证各组件连通性"},
    {"step": 7, "key": "finish",      "title": "完成检查",       "description": "完成初始化并启动"},
]


# 向导状态（内存）
_WIZARD_STATE: Dict[str, Any] = {
    "current_step": 0,
    "total_steps": len(WIZARD_STEPS),
    "completed_steps": [],
    "config": {},
    "started_at": time.strftime("%Y-%m-%d %H:%M:%S"),
    "finished_at": None,
    "status": "not_started",
}


def get_wizard_status() -> Dict[str, Any]:
    """获取向导当前状态。"""
    steps_detail = []
    for s in WIZARD_STEPS:
        done = s["step"] in _WIZARD_STATE["completed_steps"]
        steps_detail.append({
            "step": s["step"], "key": s["key"], "title": s["title"],
            "description": s["description"], "done": done,
            "active": s["step"] == _WIZARD_STATE["current_step"],
        })
    return {
        **_WIZARD_STATE,
        "steps": steps_detail,
        "progress": round(len(_WIZARD_STATE["completed_steps"]) / len(WIZARD_STEPS) * 100, 1),
    }


def wizard_step_submit(step: int, data: Dict[str, Any]) -> Dict[str, Any]:
    """提交向导某一步的数据。"""
    if step < 1 or step > len(WIZARD_STEPS):
        return {"error": f"无效步骤: {step}"}
    step_key = WIZARD_STEPS[step - 1]["key"]
    _WIZARD_STATE["config"][step_key] = data
    if step not in _WIZARD_STATE["completed_steps"]:
        _WIZARD_STATE["completed_steps"].append(step)
    _WIZARD_STATE["current_step"] = min(step + 1, len(WIZARD_STEPS))
    if len(_WIZARD_STATE["completed_steps"]) == len(WIZARD_STEPS):
        _WIZARD_STATE["status"] = "finished"
        _WIZARD_STATE["finished_at"] = time.strftime("%Y-%m-%d %H:%M:%S")
    else:
        _WIZARD_STATE["status"] = "in_progress"
    return {"ok": True, "step": step, "next_step": _WIZARD_STATE["current_step"],
            "status": _WIZARD_STATE["status"]}


def wizard_reset() -> Dict[str, Any]:
    """重置向导。"""
    _WIZARD_STATE.clear()
    _WIZARD_STATE.update({
        "current_step": 0, "total_steps": len(WIZARD_STEPS),
        "completed_steps": [], "config": {},
        "started_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "finished_at": None, "status": "not_started",
    })
    return {"ok": True, "message": "向导已重置"}


# =========================================================================== #
# 2. 配置文件管理
# =========================================================================== #
CONFIG_TEMPLATE: Dict[str, str] = {
    "AI_HACKING_ENV": "production",
    "AI_HACKING_HOST": "0.0.0.0",
    "AI_HACKING_PORT": "8000",
    "AI_HACKING_SECRET_KEY": "<auto-generated>",
    "AI_HACKING_DEBUG": "false",
    "AI_HACKING_LOG_LEVEL": "INFO",
    "AI_HACKING_DB_PATH": "./data/app.db",
    "AI_HACKING_REDIS_URL": "redis://localhost:6379/0",
    "AI_HACKING_JWT_ALG": "HS256",
    "AI_HACKING_JWT_EXPIRE": "86400",
    "AI_HACKING_CORS_ORIGINS": "*",
    "AI_HACKING_MAX_WORKERS": "4",
    "AI_HACKING_UPLOAD_DIR": "./uploads",
    "AI_HACKING_BACKUP_DIR": "./backups",
}

# 配置历史快照
_CONFIG_HISTORY: List[Dict[str, Any]] = []


def generate_env_file(config: Optional[Dict[str, str]] = None) -> str:
    """生成 .env 文件内容。"""
    merged = {**CONFIG_TEMPLATE, **(config or {})}
    if merged.get("AI_HACKING_SECRET_KEY") in ("<auto-generated>", ""):
        merged["AI_HACKING_SECRET_KEY"] = secrets.token_hex(32)
    lines = [f"# Generated at {time.strftime('%Y-%m-%d %H:%M:%S')}", ""]
    for k, v in merged.items():
        lines.append(f"{k}={v}")
    return "\n".join(lines)


def validate_config(config: Dict[str, Any]) -> Dict[str, Any]:
    """验证配置项合法性。"""
    errors: List[str] = []
    warnings: List[str] = []

    port = config.get("AI_HACKING_PORT", "8000")
    try:
        p = int(port)
        if p < 1 or p > 65535:
            errors.append(f"端口 {p} 超出范围 (1-65535)")
    except (ValueError, TypeError):
        errors.append(f"端口不是数字: {port}")

    secret = config.get("AI_HACKING_SECRET_KEY", "")
    if len(secret) < 16:
        warnings.append("SECRET_KEY 长度小于 16 字节，生产环境建议 >= 32")
    if config.get("AI_HACKING_ENV") == "production" and config.get("AI_HACKING_DEBUG") == "true":
        errors.append("生产环境不应开启 DEBUG 模式")
    if config.get("AI_HACKING_ENV") == "production" and config.get("AI_HACKING_CORS_ORIGINS") == "*":
        warnings.append("生产环境 CORS 不应使用通配符 *")

    return {"valid": len(errors) == 0, "errors": errors, "warnings": warnings}


def backup_config(config: Dict[str, Any], label: str = "") -> Dict[str, Any]:
    """备份配置。"""
    snap = {
        "snapshot_id": hashlib.sha256(f"{time.time()}{label}".encode()).hexdigest()[:16],
        "label": label,
        "captured_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "config": config,
    }
    _CONFIG_HISTORY.append(snap)
    return {"ok": True, "snapshot_id": snap["snapshot_id"], "label": label}


def list_config_backups() -> List[Dict[str, Any]]:
    """列出配置备份。"""
    return [
        {"snapshot_id": s["snapshot_id"], "label": s["label"],
         "captured_at": s["captured_at"]}
        for s in reversed(_CONFIG_HISTORY)
    ]


def compare_configs(c1: Dict[str, Any], c2: Dict[str, Any]) -> Dict[str, Any]:
    """对比两份配置差异。"""
    all_keys = set(c1.keys()) | set(c2.keys())
    diffs: List[Dict[str, str]] = []
    for k in sorted(all_keys):
        v1 = c1.get(k, "<missing>")
        v2 = c2.get(k, "<missing>")
        if v1 != v2:
            diffs.append({"key": k, "old": str(v1), "new": str(v2)})
    return {"total_diff": len(diffs), "diffs": diffs}


# =========================================================================== #
# 3. 数据库初始化（内存模拟）
# =========================================================================== #
# 模拟的表结构
MOCK_SCHEMA: List[Dict[str, Any]] = [
    {"table": "users",          "columns": ["id INTEGER PK", "username TEXT UNIQUE", "password_hash",
                                          "role TEXT", "created_at"], "indexes": ["idx_users_role"]},
    {"table": "tasks",          "columns": ["task_id TEXT PK", "kind TEXT", "status TEXT",
                                          "created_at", "finished_at", "result"], "indexes": ["idx_tasks_status"]},
    {"table": "deploy_records", "columns": ["id INTEGER PK", "version TEXT", "environment TEXT",
                                          "operator TEXT", "result TEXT", "created_at"], "indexes": ["idx_deploy_env"]},
    {"table": "system_config",  "columns": ["key TEXT PK", "value TEXT", "updated_at"], "indexes": []},
    {"table": "audit_logs",     "columns": ["id INTEGER PK", "actor TEXT", "action TEXT",
                                          "detail TEXT", "created_at"], "indexes": ["idx_audit_actor"]},
]

_DB_INIT_STATE: Dict[str, Any] = {
    "initialized": False,
    "initialized_at": None,
    "tables_created": [],
    "indexes_created": [],
    "seed_data": {},
    "admin_account": None,
}


def init_database(admin_username: str = "admin", admin_password: str = "admin123") -> Dict[str, Any]:
    """模拟数据库初始化。"""
    _DB_INIT_STATE["initialized"] = True
    _DB_INIT_STATE["initialized_at"] = time.strftime("%Y-%m-%d %H:%M:%S")
    _DB_INIT_STATE["tables_created"] = [t["table"] for t in MOCK_SCHEMA]
    _DB_INIT_STATE["indexes_created"] = [idx for t in MOCK_SCHEMA for idx in t["indexes"]]
    _DB_INIT_STATE["seed_data"] = {
        "system_config": [
            ("site_name", "AI Hacking Agent"),
            ("version", "20.1.0"),
            ("default_locale", "zh-CN"),
        ],
    }
    pwd_hash = hashlib.sha256(admin_password.encode()).hexdigest()
    _DB_INIT_STATE["admin_account"] = {
        "username": admin_username,
        "password_hash": pwd_hash,
        "role": "superadmin",
        "must_change_password": True,
    }
    return {
        "ok": True,
        "tables_created": len(_DB_INIT_STATE["tables_created"]),
        "indexes_created": len(_DB_INIT_STATE["indexes_created"]),
        "admin": {"username": admin_username, "role": "superadmin"},
    }


def get_db_init_status() -> Dict[str, Any]:
    return dict(_DB_INIT_STATE)


# =========================================================================== #
# 4. 数据迁移
# =========================================================================== #
MIGRATION_HISTORY: List[Dict[str, Any]] = [
    {"version": "18.0.0", "upgraded_at": "2026-06-01 10:00:00", "status": "done",
     "note": "初始版本"},
    {"version": "19.0.0", "upgraded_at": "2026-07-15 14:30:00", "status": "done",
     "note": "新增数据安全模块"},
    {"version": "20.0.0", "upgraded_at": "2026-08-20 09:15:00", "status": "done",
     "note": "Round 20 大版本"},
]


def plan_migration(from_version: str, to_version: str) -> Dict[str, Any]:
    """生成迁移计划。"""
    steps = [
        f"1. 备份当前数据 (v{from_version})",
        f"2. 下载新版本 v{to_version}",
        "3. 运行 schema 迁移脚本",
        "4. 转换数据格式",
        "5. 验证数据完整性",
        "6. 重启服务",
        "7. 健康检查",
    ]
    return {
        "from_version": from_version,
        "to_version": to_version,
        "estimated_duration_min": 15,
        "steps": steps,
        "rollback_plan": [
            "1. 停止服务",
            "2. 恢复备份",
            "3. 回滚 schema",
            "4. 重启旧版本",
        ],
    }


def run_migration_simulation(from_version: str, to_version: str) -> Dict[str, Any]:
    """模拟执行迁移。"""
    plan = plan_migration(from_version, to_version)
    log: List[Dict[str, Any]] = []
    for i, step in enumerate(plan["steps"], 1):
        log.append({"step": i, "action": step, "status": "done",
                    "timestamp": time.strftime("%Y-%m-%d %H:%M:%S")})
    MIGRATION_HISTORY.append({
        "version": to_version,
        "upgraded_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "status": "done",
        "note": f"自动模拟迁移 from {from_version}",
    })
    return {"plan": plan, "log": log, "success": True}


# =========================================================================== #
# 5. 服务管理
# =========================================================================== #
_SERVICE_STATE: Dict[str, Any] = {
    "status": "running",
    "started_at": time.strftime("%Y-%m-%d %H:%M:%S"),
    "uptime_seconds": 0,
    "auto_start": True,
    "restart_count": 0,
    "health": "healthy",
    "pid": os.getpid(),
    "log_tail": [
        f"[{time.strftime('%H:%M:%S')}] INFO  uvicorn running on http://0.0.0.0:8000",
        f"[{time.strftime('%H:%M:%S')}] INFO  Application startup complete.",
    ],
}


def service_action(action: str) -> Dict[str, Any]:
    """模拟服务操作。"""
    action = action.lower()
    now = time.strftime("%Y-%m-%d %H:%M:%S")
    if action == "start":
        if _SERVICE_STATE["status"] == "running":
            return {"ok": False, "message": "服务已在运行"}
        _SERVICE_STATE["status"] = "running"
        _SERVICE_STATE["started_at"] = now
        _SERVICE_STATE["log_tail"].append(f"[{now}] INFO  Service started")
        return {"ok": True, "status": "running"}
    if action == "stop":
        _SERVICE_STATE["status"] = "stopped"
        _SERVICE_STATE["log_tail"].append(f"[{now}] INFO  Service stopped")
        return {"ok": True, "status": "stopped"}
    if action == "restart":
        _SERVICE_STATE["restart_count"] += 1
        _SERVICE_STATE["status"] = "running"
        _SERVICE_STATE["started_at"] = now
        _SERVICE_STATE["log_tail"].append(f"[{now}] INFO  Service restarted (#{_SERVICE_STATE['restart_count']})")
        return {"ok": True, "status": "running", "restart_count": _SERVICE_STATE["restart_count"]}
    if action == "status":
        return {"ok": True, **_SERVICE_STATE}
    if action == "autostart":
        _SERVICE_STATE["auto_start"] = not _SERVICE_STATE["auto_start"]
        return {"ok": True, "auto_start": _SERVICE_STATE["auto_start"]}
    return {"error": f"未知操作: {action}"}


def service_health_check() -> Dict[str, Any]:
    """模拟健康检查。"""
    return {
        "status": _SERVICE_STATE["health"],
        "checked_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "checks": [
            {"name": "process_alive", "status": "ok", "detail": f"pid={_SERVICE_STATE['pid']}"},
            {"name": "port_listening", "status": "ok", "detail": "8000/tcp"},
            {"name": "disk_space", "status": "ok", "detail": "230GB free"},
            {"name": "memory", "status": "ok", "detail": "156MB RSS"},
        ],
    }
